[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "LLM Learn"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
